In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
df = pd.read_csv("./imessages_high_sierra.csv")

In [3]:
df.head()

,text,handle_id,date,message_date,timestamp,month,year,is_sent,message_id,phone_number,chat_id
0,Hey ruth this is elvis,156,2021-03-26,638513440582854784,2021-03-26 21:50:40,3,2021,1,22277,14805129523,156.0
1,hiiii!,156,2021-03-26,638513465161326464,2021-03-26 21:51:05,3,2021,0,22278,14805129523,156.0
2,hows ur night going ?,156,2021-03-26,638513774818752000,2021-03-26 21:56:14,3,2021,0,22279,14805129523,156.0
3,"Im good, just finished working out",156,2021-03-26,638514227370322176,2021-03-26 22:03:47,3,2021,1,22280,14805129523,156.0
4,Probably just gonna work on my research paper ...,156,2021-03-26,638514248533245056,2021-03-26 22:04:08,3,2021,1,22281,14805129523,156.0

In [4]:
data = df[["text", "is_sent"]][1:].to_numpy()

In [5]:
i = 0
questions = []
answers = []
delim = " <|brk|> "
while (i < len(data)):
    q = ""
    a = ""
    
    while (i < len(data)):
        text = data[i][0]
        is_sent = data[i][1]
        if is_sent == 1:
            break;
        q += text + delim
        i += 1
    q = q[:-len(delim)]
    
    while (i < len(data)):
        text = data[i][0]
        is_sent = data[i][1]
        if is_sent == 0:
            break;
        a += text + delim
        i += 1
    a = a[:-len(delim)]
    
    questions.append(q)
    answers.append(a)
# print(questions[:2])

In [6]:
df_new = pd.DataFrame({"questions": questions, "answers": answers})

In [7]:
df_new.head()

,questions,answers
0,hiiii! <|brk|> hows ur night going ?,"Im good, just finished working out <|brk|> Pro..."
1,"did some work for some classes earlier, just f...",oooh we still catching up on lectures big mood...
2,yeah haha I have a midterm next week :/// down...,ohhh what kinda theory ðŸ‘€ <|brk|> i only have a...
3,omg ya Iâ€™m only a baby genshin player and play...,u should totally buy it on your laptop its onl...
4,omg I thought it was 50 ðŸ˜­,im p sure its only 25 <|brk|> maybe it changed

In [8]:
df_new.to_csv('./questions_answers.csv', index = False, encoding='utf-8')